name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/nex-reference/index.json
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release Common.Logging
      - name: Create the package
        run: dotnet pack --configuration Release Common.Logging
      - name: Publish the package to GPR
        run: dotnet nuget push Common.Logging/bin/Release/*.nupkg
